# Copyright 1999-2023 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.8.4.0.9999
#hackport: flags: -werror

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Type-safe, feature-complete SQL query and manipulation interface for Haskell"
HOMEPAGE="https://travis.athougies.net/projects/beam.html"

LICENSE="MIT"
SLOT="0/${PV}"
KEYWORDS="~amd64"

RDEPEND="
	>=dev-haskell/aeson-0.11:=[profile?] <dev-haskell/aeson-2.2
	>=dev-haskell/dlist-0.7.1.2:=[profile?] <dev-haskell/dlist-1.1
	>=dev-haskell/free-4.12:=[profile?] <dev-haskell/free-5.3
	>=dev-haskell/hashable-1.2.4.0:=[profile?] <dev-haskell/hashable-1.5
	=dev-haskell/microlens-0.4*:=[profile?]
	=dev-haskell/network-uri-2.6*:=[profile?]
	=dev-haskell/scientific-0.3*:=[profile?]
	=dev-haskell/tagged-0.8*:=[profile?]
	>=dev-haskell/text-1.2.2.0:=[profile?] <dev-haskell/text-2.1
	>=dev-haskell/vector-0.11:=[profile?] <dev-haskell/vector-0.14
	>=dev-haskell/vector-sized-0.5:=[profile?] <dev-haskell/vector-sized-1.6
	>=dev-lang/ghc-8.8.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.0.0.0
	test? (
		dev-haskell/tasty
		dev-haskell/tasty-hunit
	)
"

src_configure() {
	haskell-cabal_src_configure \
		--flag=-werror
}
