# Copyright 1999-2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.0.0.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="\"Conversion\" instances for the \"text\" library "
HOMEPAGE="https://github.com/nikita-volkov/conversion-text "

LICENSE="MIT"
SLOT="0/${PV}"
KEYWORDS="~amd64"

CABAL_CHDEPS=(
	'bytestring >= 0.10 && < 0.12' 'bytestring >= 0.10'
	)

RDEPEND=">=dev-haskell/base-prelude-0.1.19:=[profile?] <dev-haskell/base-prelude-2:=[profile?]
	>=dev-haskell/conversion-1:=[profile?] <dev-haskell/conversion-2:=[profile?]
	>=dev-haskell/conversion-bytestring-1.0.1.1:=[profile?] <dev-haskell/conversion-bytestring-2:=[profile?]
	>=dev-haskell/text-1:=[profile?] <dev-haskell/text-3:=[profile?]
	>=dev-lang/ghc-9.0.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
"
