# Copyright 1999-2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header:  $

# ebuild generated by hackport 0.2.14

EAPI="3"

CABAL_FEATURES="bin"
inherit haskell-cabal

DESCRIPTION="Dependently Typed Functional Programming Language"
HOMEPAGE="http://www.idris-lang.org/"
SRC_URI="http://hackage.haskell.org/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=""
DEPEND="${RDEPEND}
		dev-haskell/binary
		>=dev-haskell/cabal-1.6
		>=dev-lang/epic-0.9.2
		dev-haskell/haskeline
		dev-haskell/mtl
		dev-haskell/parsec
		dev-haskell/transformers
		>=dev-lang/ghc-6.10.1"
