# Copyright 1999-2018 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=6

# ebuild generated by hackport 0.5.3.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour" # Broken test-suite: heeds a port to cabal-2
inherit haskell-cabal

DESCRIPTION="Cabal support for creating Mac OSX application bundles"
HOMEPAGE="https://github.com/danfran/cabal-macosx"
SRC_URI="https://hackage.haskell.org/package/${P}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RESTRICT=test # Data constructor not in scope: ExecutableScopeUnknown

RDEPEND=">=dev-haskell/cabal-1.6:=[profile?]
	dev-haskell/fgl:=[profile?]
	dev-haskell/hscolour:=[profile?]
	dev-haskell/parsec:=[profile?]
	dev-haskell/text:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.8
"
