# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=7

# ebuild generated by hackport 0.6.7.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Rose trees with cached and accumulating monoidal annotations"
HOMEPAGE="https://hackage.haskell.org/package/dual-tree"
SRC_URI="https://hackage.haskell.org/package/${P}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"

RDEPEND=">=dev-haskell/monoid-extras-0.6:=[profile?] <dev-haskell/monoid-extras-0.7:=[profile?]
	>=dev-haskell/newtype-generics-0.6:=[profile?] <dev-haskell/newtype-generics-0.7:=[profile?]
	>=dev-haskell/semigroups-0.8:=[profile?] <dev-haskell/semigroups-0.20:=[profile?]
	>=dev-lang/ghc-8.4.3:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-2.2.0.1
	test? ( dev-haskell/quickcheck
		dev-haskell/testing-feat )
"

src_prepare() {
	default

	cabal_chdeps \
		'base >= 4.3 && < 4.16' 'base >= 4.3'
}
