# Copyright 1999-2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.0.0.9999

CABAL_HACKAGE_REVISION=4

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Tagged binary serialisation"
HOMEPAGE="https://hackage.haskell.org/package/binary-tagged"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64"

RDEPEND=">=dev-haskell/structured-0.1.1:=[profile?] <dev-haskell/structured-0.1.2:=[profile?]
	>=dev-haskell/tagged-0.8.6:=[profile?] <dev-haskell/tagged-0.9:=[profile?]
	>=dev-lang/ghc-9.0.2:=
	|| (
		( >=dev-haskell/base16-bytestring-0.1.1.6 <dev-haskell/base16-bytestring-0.2 )
		( >=dev-haskell/base16-bytestring-1.0.0.0 <dev-haskell/base16-bytestring-1.1 )
	)
	dev-haskell/base16-bytestring:=[profile?]
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
	test? ( >=dev-haskell/binary-instances-1 <dev-haskell/binary-instances-1.1
		>=dev-haskell/quickcheck-2.14 <dev-haskell/quickcheck-2.15
		dev-haskell/quickcheck-instances
		>=dev-haskell/singleton-bool-0.1.5 <dev-haskell/singleton-bool-0.2
		dev-haskell/tasty
		dev-haskell/tasty-hunit
		dev-haskell/tasty-quickcheck )
"
