# Copyright 1999-2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.0.0.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Treemap visualiser for GHC prof files"
HOMEPAGE="https://github.com/jaspervdj/profiteur"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64"
IUSE="embed-data-files"

CABAL_CHDEPS=(
	'aeson                >= 0.6  && < 2.2' 'aeson >= 0.6'
	'bytestring           >= 0.9  && < 0.12' 'bytestring >= 0.9'
	'text                 >= 0.11 && < 2.1' 'text >= 0.11'
)

RDEPEND=">=dev-haskell/aeson-0.6:=[profile?]
	>=dev-haskell/ghc-prof-1.3:=[profile?] <dev-haskell/ghc-prof-1.5:=[profile?]
	>=dev-haskell/js-jquery-3.1:=[profile?] <dev-haskell/js-jquery-3.4:=[profile?]
	>=dev-haskell/scientific-0.3:=[profile?] <dev-haskell/scientific-0.4:=[profile?]
	>=dev-haskell/text-0.11:=[profile?]
	>=dev-haskell/unordered-containers-0.2:=[profile?] <dev-haskell/unordered-containers-0.3:=[profile?]
	>=dev-haskell/vector-0.10:=[profile?] <dev-haskell/vector-0.14:=[profile?]
	>=dev-lang/ghc-9.0.2:=
	embed-data-files? ( >=dev-haskell/file-embed-0.0.10:=[profile?] <dev-haskell/file-embed-0.0.12:=[profile?] )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag embed-data-files embed-data-files)
}
