# Copyright 1999-2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.1.0.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="ghci-dap is a GHCi having DAP interface"
HOMEPAGE="https://github.com/phoityne/ghci-dap"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64"

RDEPEND="
	dev-haskell/ghc-paths:=[profile?]
	dev-haskell/haskeline:=[profile?]
	>=dev-haskell/haskell-dap-0.0.15.0:=[profile?]
	dev-haskell/text:=[profile?]
	>=dev-lang/ghc-9.4.5:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.8.1.0
"
