# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header:  $

# ebuild generated by hackport 0.2.17.9999

EAPI=4

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="A fast, iteratee-based, epoll-enabled web server for the Snap Framework"
HOMEPAGE="http://snapframework.com/"
SRC_URI="http://hackage.haskell.org/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="=dev-haskell/attoparsec-0.10*[profile?]
		=dev-haskell/attoparsec-enumerator-0.3*[profile?]
		=dev-haskell/binary-0.5*[profile?]
		>=dev-haskell/blaze-builder-0.2.1.4[profile?]
		<dev-haskell/blaze-builder-0.4[profile?]
		>=dev-haskell/blaze-builder-enumerator-0.2.0[profile?]
		<dev-haskell/blaze-builder-enumerator-0.3[profile?]
		dev-haskell/bytestring-nums[profile?]
		>=dev-haskell/case-insensitive-0.3[profile?]
		<dev-haskell/case-insensitive-0.5[profile?]
		=dev-haskell/directory-tree-0.10*[profile?]
		>=dev-haskell/enumerator-0.4.15[profile?]
		<dev-haskell/enumerator-0.5[profile?]
		>=dev-haskell/monadcatchio-transformers-0.2.1[profile?]
		<dev-haskell/monadcatchio-transformers-0.4[profile?]
		=dev-haskell/mtl-2*[profile?]
		=dev-haskell/murmur-hash-0.1*[profile?]
		=dev-haskell/network-2.3*[profile?]
		=dev-haskell/psqueue-1.1*[profile?]
		=dev-haskell/snap-core-0.8*[profile?]
		=dev-haskell/text-0.11*[profile?]
		>=dev-haskell/time-1.0[profile?]
		<dev-haskell/time-1.5[profile?]
		>=dev-haskell/transformers-0.2[profile?]
		<dev-haskell/transformers-0.4[profile?]
		>=dev-haskell/unix-compat-0.2[profile?]
		<dev-haskell/unix-compat-0.4[profile?]
		>=dev-haskell/vector-0.7[profile?]
		<dev-haskell/vector-0.10[profile?]
		>=dev-haskell/vector-algorithms-0.4[profile?]
		<dev-haskell/vector-algorithms-0.6[profile?]
		>=dev-lang/ghc-6.12.1"
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.6"
