# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header:  $

# ebuild generated by hackport 0.2.9

CABAL_FEATURES="lib profile haddock hscolour"
inherit haskell-cabal

DESCRIPTION="Leksah tool kit"
HOMEPAGE="http://www.leksah.org"
SRC_URI="http://hackage.haskell.org/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="GPL-2"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/cabal-1.6.0
		>=dev-haskell/glib-0.10.0
		>=dev-haskell/gtk-0.10.0
		>=dev-haskell/mtl-1.1.0.2
		>=dev-haskell/parsec-2.1.0.1
		>=dev-lang/ghc-6.10.1"
DEPEND="${RDEPEND}" # has Cabal as an RDEPEND already
