# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.7.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Integrate Hedgehog and Hspec!"
HOMEPAGE="https://github.com/parsonsmatt/hspec-hedgehog#readme"
SRC_URI="https://hackage.haskell.org/package/${P}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64"

RDEPEND=">=dev-haskell/hedgehog-1.0.2:=[profile?] <dev-haskell/hedgehog-2:=[profile?]
	>=dev-haskell/hspec-2.5.8:=[profile?] <dev-haskell/hspec-3:=[profile?]
	>=dev-haskell/hspec-core-2.5.8:=[profile?] <dev-haskell/hspec-core-3:=[profile?]
	>=dev-haskell/hunit-1.5:=[profile?] <dev-haskell/hunit-2:=[profile?]
	>=dev-haskell/quickcheck-2.9.2:2=[profile?] <dev-haskell/quickcheck-3:2=[profile?]
	>=dev-haskell/splitmix-0.0.1:=[profile?] <dev-haskell/splitmix-1:=[profile?]
	>=dev-lang/ghc-8.4.3:=[profile?]
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-2.2.0.1
"
