# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.3.9999

CABAL_FEATURES="bin lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="A web interface for the hledger accounting tool."
HOMEPAGE="http://hledger.org"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="GPL-2"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="=dev-haskell/blaze-html-0.4*:=[profile?]
		dev-haskell/cabal-file-th:=[profile?]
		dev-haskell/clientsession:=[profile?]
		>=dev-haskell/cmdargs-0.9.1:=[profile?]
		<dev-haskell/cmdargs-0.10:=[profile?]
		dev-haskell/hamlet:=[profile?]
		~dev-haskell/hledger-0.18.2:=[profile?]
		~dev-haskell/hledger-lib-0.18.2:=[profile?]
		dev-haskell/hunit:=[profile?]
		=dev-haskell/io-storage-0.3*:=[profile?]
		dev-haskell/network-conduit:=[profile?]
		dev-haskell/parsec:=[profile?]
		>=dev-haskell/regexpr-0.5.1:=[profile?]
		>=dev-haskell/safe-0.2:=[profile?]
		dev-haskell/shakespeare-text:=[profile?]
		=dev-haskell/text-0.11*:=[profile?]
		>=dev-haskell/transformers-0.2:=[profile?]
		<dev-haskell/transformers-0.4:=[profile?]
		dev-haskell/wai:=[profile?]
		dev-haskell/wai-extra:=[profile?]
		dev-haskell/warp:=[profile?]
		dev-haskell/yaml:=[profile?]
		=dev-haskell/yesod-1.0*:=[profile?]
		dev-haskell/yesod-core:=[profile?]
		dev-haskell/yesod-default:=[profile?]
		dev-haskell/yesod-static:=[profile?]
		>=dev-lang/ghc-7.0.1:="
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.6"
