# Copyright 1999-2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header:  $

# ebuild generated by hackport 0.2.13

EAPI="3"

CABAL_FEATURES="lib profile haddock hscolour hoogle"
inherit haskell-cabal

DESCRIPTION="Provides some basic WAI handlers and middleware."
HOMEPAGE="http://github.com/snoyberg/wai-extra"
SRC_URI="http://hackage.haskell.org/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE="test"

RDEPEND="<dev-haskell/blaze-builder-0.4
		=dev-haskell/blaze-builder-enumerator-0.2*
		>=dev-haskell/case-insensitive-0.2
		=dev-haskell/data-default-0.3*
		=dev-haskell/enumerator-0.4*
		>=dev-haskell/fast-logger-0.0.1
		=dev-haskell/http-types-0.6*
		<dev-haskell/network-2.4
		<dev-haskell/text-0.12
		>=dev-haskell/time-1.1.4
		=dev-haskell/transformers-0.2*
		=dev-haskell/wai-0.4*
		=dev-haskell/zlib-bindings-0.0*
		=dev-haskell/zlib-enum-0.2*
		>=dev-lang/ghc-6.12.1"
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.6
		test? ( >=dev-haskell/hspec-0.8
				dev-haskell/hunit
				dev-haskell/wai-test
				dev-haskell/zlib
		)"

src_prepare() {
	mkdir -p "${S}/test/requests"
	cp "${FILESDIR}/wai-extra-0.4.5.1/test/WaiExtraTest.hs" "${S}/test"
	cp "${FILESDIR}/wai-extra-0.4.5.1/test/requests/dalvik-request" "${S}/test/requests"
}

src_configure() {
	cabal_src_configure $(use_enable test tests)
}
