# Copyright 1999-2018 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

EAPI=6

# ebuild generated by hackport 0.5.6

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Streaming parser/renderer for the RSS standard"
HOMEPAGE="http://hackage.haskell.org/package/rss-conduit"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="public-domain"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="enable-hlint-test"

RDEPEND=">=dev-haskell/atom-conduit-0.5:=[profile?]
	>=dev-haskell/conduit-1.3:=[profile?]
	dev-haskell/conduit-combinators:=[profile?]
	dev-haskell/dublincore-xml-conduit:=[profile?]
	dev-haskell/lens-simple:=[profile?]
	dev-haskell/safe:=[profile?]
	dev-haskell/safe-exceptions:=[profile?]
	dev-haskell/semigroups:=[profile?]
	dev-haskell/singletons:=[profile?]
	dev-haskell/text:=[profile?]
	>=dev-haskell/timerep-2.0:=[profile?]
	>=dev-haskell/uri-bytestring-0.2:=[profile?]
	>=dev-haskell/vinyl-0.9:=[profile?]
	>=dev-haskell/xml-conduit-1.5:=[profile?]
	dev-haskell/xml-types:=[profile?]
	>=dev-lang/ghc-7.10.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.22.2.0
	test? ( dev-haskell/blaze-builder
		dev-haskell/data-default
		dev-haskell/hlint
		dev-haskell/mono-traversable
		dev-haskell/quickcheck
		dev-haskell/quickcheck-instances
		dev-haskell/resourcet
		dev-haskell/tasty
		dev-haskell/tasty-hunit
		dev-haskell/tasty-quickcheck )
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag enable-hlint-test enable-hlint-test)
}
