# Copyright 1999-2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header:  $

# ebuild generated by hackport 0.2.14

EAPI="3"

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Authentication methods for Haskell web applications."
HOMEPAGE="http://github.com/yesodweb/authenticate"
SRC_URI="http://hackage.haskell.org/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/aeson-0.3.2.11
		>=dev-haskell/attoparsec-0.9
		=dev-haskell/base64-bytestring-0.1*
		<dev-haskell/blaze-builder-0.4
		>=dev-haskell/case-insensitive-0.2
		=dev-haskell/enumerator-0.4*
		<dev-haskell/failure-0.2
		<dev-haskell/http-enumerator-0.8
		=dev-haskell/http-types-0.6*
		<dev-haskell/network-2.4
		=dev-haskell/rsa-1.0*
		<dev-haskell/sha-1.6
		=dev-haskell/tagsoup-0.12*
		<dev-haskell/text-1.0
		>=dev-haskell/time-1.1
		=dev-haskell/tls-0.8*
		<dev-haskell/transformers-0.3
		dev-haskell/unordered-containers
		=dev-haskell/xml-enumerator-0.4*
		>=dev-lang/ghc-6.10.4"
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.6"
