# Copyright 1999-2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.0.0.9999
#hackport: flags: executables:examples

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="FFI bindings for libopusfile"
HOMEPAGE="https://hackage.haskell.org/package/opusfile"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64"
IUSE="examples"

CABAL_CHBINS=(
	'example-openal' "haskell-${PN}-example"
)

RDEPEND=">=dev-lang/ghc-9.0.2:=
	media-libs/opusfile
	examples? ( dev-haskell/openal:=[profile?]
			dev-haskell/statevar:=[profile?] )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag examples executables)
}
