# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header:  $

# ebuild generated by hackport 0.2.9
EAPI="2"

CABAL_FEATURES="bin lib profile haddock hscolour"
inherit haskell-cabal

DESCRIPTION="Multithread interactive input/search framework for Manatee"
HOMEPAGE="http://hackage.haskell.org/package/manatee-anything"
SRC_URI="http://hackage.haskell.org/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="GPL-3"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="dev-haskell/dataenc
		=dev-haskell/dbus-client-0.3*
		dev-haskell/dbus-core
		>=dev-haskell/gio-0.12.0
		>=dev-haskell/googlesuggest-0.0.3
		>=dev-haskell/gtk-0.12.0
		>=dev-haskell/manatee-core-0.0.8
		>=dev-haskell/mtl-1.1.0.2
		>=dev-haskell/network-2.2.1.5
		>=dev-haskell/proc-0.0.8
		>=dev-haskell/regex-tdfa-1.1.2
		dev-haskell/split
		>=dev-haskell/stm-2.1.2.0
		>=dev-haskell/text-0.7.1.0
		>=dev-haskell/utf8-string-0.3.4
		>=dev-lang/ghc-6.12.1"
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.6"
