# Copyright 1999-2019 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

EAPI=6

# ebuild generated by hackport 0.5.6

CABAL_FEATURES=""
inherit haskell-cabal

DESCRIPTION="Lambdabot is a development tool and advanced IRC bot"
HOMEPAGE="https://wiki.haskell.org/Lambdabot"
SRC_URI="https://hackage.haskell.org/package/${P}/${P}.tar.gz"

LICENSE="GPL-2"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/lambdabot-core-5.1.0.1:= <dev-haskell/lambdabot-core-5.2:=
	>=dev-haskell/lambdabot-haskell-plugins-5.1.0.1:= <dev-haskell/lambdabot-haskell-plugins-5.2:=
	>=dev-haskell/lambdabot-irc-plugins-5.1.0.1:= <dev-haskell/lambdabot-irc-plugins-5.2:=
	>=dev-haskell/lambdabot-misc-plugins-5.1.0.1:= <dev-haskell/lambdabot-misc-plugins-5.2:=
	>=dev-haskell/lambdabot-novelty-plugins-5.1.0.1:= <dev-haskell/lambdabot-novelty-plugins-5.2:=
	>=dev-haskell/lambdabot-reference-plugins-5.1.0.1:= <dev-haskell/lambdabot-reference-plugins-5.2:=
	>=dev-haskell/lambdabot-social-plugins-5.1.0.1:= <dev-haskell/lambdabot-social-plugins-5.2:=
	>=dev-haskell/mtl-2:=
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.8
"
