# Copyright 1999-2024 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.8.5.1.9999
#hackport: flags: -corelint

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Disambiguate obvious uses of effects"
HOMEPAGE="https://github.com/polysemy-research/polysemy#readme"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64"

GHC_BOOTSTRAP_PACKAGES=(
	cabal-doctest
)

CABAL_CHDEPS=(
	'doctest >=0.16.0.1 && <0.23' 'doctest >=0.16.0.1'
)

RDEPEND=">=dev-haskell/ghc-tcplugins-extra-0.3:=[profile?] <dev-haskell/ghc-tcplugins-extra-0.5:=[profile?]
	>=dev-haskell/polysemy-1.7:=[profile?]
	>=dev-haskell/syb-0.7:=[profile?] <dev-haskell/syb-0.8:=[profile?]
	>=dev-lang/ghc-9.0.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0 <dev-haskell/cabal-3.11
	>=dev-haskell/cabal-doctest-1.0.6 <dev-haskell/cabal-doctest-1.1
	test? ( >=dev-haskell/doctest-0.16.0.1
		>=dev-haskell/hspec-2.6.0 <dev-haskell/hspec-3
		dev-haskell/hspec-discover
		>=dev-haskell/inspection-testing-0.4.2 <dev-haskell/inspection-testing-0.6
		>=dev-haskell/should-not-typecheck-2.1.0 <dev-haskell/should-not-typecheck-3 )
"

src_configure() {
	haskell-cabal_src_configure \
		--flag=-corelint
}
