# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.2.9999

CABAL_FEATURES="bin lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Conversion of LaTeX math formulas to MathML or OMML"
HOMEPAGE="http://github.com/jgm/texmath"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="GPL-2"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="cgi executable"

RESTRICT=test # missing file

RDEPEND="dev-haskell/mtl:=[profile?]
	>=dev-haskell/pandoc-types-1.12.3.3:=[profile?]
	>=dev-haskell/parsec-3:=[profile?]
	dev-haskell/syb:=[profile?]
	dev-haskell/xml:=[profile?]
	>=dev-lang/ghc-7.4.1:=
	cgi? ( dev-haskell/cgi:=[profile?]
		dev-haskell/json:=[profile?]
		dev-haskell/utf8-string:=[profile?] )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.10
	test? ( !cgi? ( dev-haskell/utf8-string ) )
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag cgi cgi) \
		$(cabal_flag executable executable)
}
