# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

# ebuild generated by hackport 0.2.17.9999

EAPI=4

CABAL_FEATURES="lib profile haddock hscolour hoogle"
inherit haskell-cabal

DESCRIPTION="Fast JSON parsing and encoding"
HOMEPAGE="https://github.com/bos/aeson"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE="test"

RDEPEND=">=dev-haskell/attoparsec-0.8.6.1[profile?]
		>=dev-haskell/blaze-builder-0.2.1.4[profile?]
		dev-haskell/deepseq[profile?]
		>=dev-haskell/dlist-0.2[profile?]
		>=dev-haskell/hashable-1.1.2.0[profile?]
		dev-haskell/mtl[profile?]
		dev-haskell/syb[profile?]
		>=dev-haskell/text-0.11.1.0[profile?]
		>=dev-haskell/unordered-containers-0.1.3.0[profile?]
		>=dev-haskell/vector-0.7.1[profile?]
		>=dev-lang/ghc-6.12.1"
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.8
		test? ( >=dev-haskell/cabal-1.10
			>=dev-haskell/quickcheck-2.4.0.1[profile?]
			dev-haskell/test-framework[profile?]
			dev-haskell/test-framework-quickcheck2[profile?]
		)
		"

src_configure() {
	cabal_src_configure $(use test && use_enable test tests) #395351
}
