# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

# ebuild generated by hackport 0.2.17.9999

EAPI=4

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="A fast, light-weight web server for WAI applications."
HOMEPAGE="http://github.com/yesodweb/wai"
SRC_URI="http://hackage.haskell.org/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""
RESTRICT="test"

RDEPEND=">=dev-haskell/blaze-builder-0.2.1.4[profile?]
		<dev-haskell/blaze-builder-0.4[profile?]
		=dev-haskell/blaze-builder-conduit-0.4*[profile?]
		>=dev-haskell/case-insensitive-0.2[profile?]
		=dev-haskell/conduit-0.4*[profile?]
		=dev-haskell/http-types-0.6*[profile?]
		=dev-haskell/lifted-base-0.1*[profile?]
		=dev-haskell/network-2.3*[profile?]
		=dev-haskell/network-conduit-0.4*[profile?]
		>=dev-haskell/simple-sendfile-0.1[profile?]
		<dev-haskell/simple-sendfile-0.3[profile?]
		>=dev-haskell/transformers-0.2.2[profile?]
		<dev-haskell/transformers-0.4[profile?]
		>=dev-haskell/unix-compat-0.2[profile?]
		=dev-haskell/wai-1.2*[profile?]
		>=dev-lang/ghc-6.10.1"
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.8"

src_configure() {
	cabal_src_configure $(use_enable test tests)
}
