# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

# ebuild generated by hackport 0.2.14

EAPI="3"

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Compression and decompression in the bzip2 format"
HOMEPAGE="http://hackage.haskell.org/package/bzlib"
SRC_URI="http://hackage.haskell.org/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~sparc ~x86"
IUSE=""

RDEPEND=">=dev-lang/ghc-6.8.2
		>=app-arch/bzip2-1.0"
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.6"

# Workaround this error when compiling with ghc 7.0.4:
# Stream.hsc:62:21: error: missing binary operator before token "("
CABAL_EXTRA_CONFIGURE_FLAGS="--hsc2hs-options=--include=${S}/dist/build/autogen/cabal_macros.h"
