# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

EAPI=6

# ebuild generated by hackport 0.5

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Wrapper around email-validate library adding instances for common type classes"
HOMEPAGE="https://github.com/cdepillabout/emailaddress#readme"
SRC_URI="https://hackage.haskell.org/package/${P}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/aeson-0.9:=[profile?]
	>=dev-haskell/bifunctors-5:=[profile?]
	>=dev-haskell/email-validate-2:=[profile?]
	>=dev-haskell/http-api-data-0.2:=[profile?]
	>=dev-haskell/opaleye-0.4:=[profile?]
	>=dev-haskell/path-pieces-0.2:=[profile?]
	>=dev-haskell/persistent-2:=[profile?]
	>=dev-haskell/postgresql-simple-0.5:=[profile?]
	>=dev-haskell/product-profunctors-0.6:=[profile?]
	>=dev-haskell/profunctors-0.5:=[profile?]
	>=dev-haskell/text-1.2:=[profile?]
	>=dev-lang/ghc-7.6.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.16.0
	test? ( dev-haskell/doctest
		dev-haskell/glob )
"
