# Copyright 1999-2020 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=7

# ebuild generated by hackport 0.6.5.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Hackage security library"
HOMEPAGE="https://github.com/haskell/hackage-security"
SRC_URI="https://hackage.haskell.org/package/${P}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="mtl21 +network-uri"

RDEPEND=">=dev-haskell/base16-bytestring-0.1.1:=[profile?] <dev-haskell/base16-bytestring-0.2:=[profile?]
	>=dev-haskell/base64-bytestring-1.0:=[profile?] <dev-haskell/base64-bytestring-1.2:=[profile?]
	>=dev-haskell/cryptohash-sha256-0.11:=[profile?] <dev-haskell/cryptohash-sha256-0.12:=[profile?]
	>=dev-haskell/ed25519-0.0:=[profile?] <dev-haskell/ed25519-0.1:=[profile?]
	>=dev-haskell/lukko-0.1:=[profile?] <dev-haskell/lukko-0.2:=[profile?]
	>=dev-haskell/old-locale-1.0:=[profile?] <dev-haskell/old-locale-1.1:=[profile?]
	>=dev-haskell/parsec-3.1:=[profile?] <dev-haskell/parsec-3.2:=[profile?]
	>=dev-haskell/tar-0.5:=[profile?] <dev-haskell/tar-0.6:=[profile?]
	>=dev-haskell/zlib-0.5:=[profile?] <dev-haskell/zlib-0.7:=[profile?]
	>=dev-lang/ghc-7.8.2:=
	<dev-haskell/cabal-3.5:=[profile?]
	mtl21? ( >=dev-haskell/mtl-2.1:=[profile?] <dev-haskell/mtl-2.2:=[profile?]
			>=dev-haskell/mtl-compat-0.2:=[profile?] <dev-haskell/mtl-compat-0.3:=[profile?] )
	!mtl21? ( >=dev-haskell/mtl-2.2:=[profile?] <dev-haskell/mtl-2.3:=[profile?] )
	network-uri? ( >=dev-haskell/network-uri-2.6:=[profile?] <dev-haskell/network-uri-2.7:=[profile?]
			>=dev-haskell/network-2.6:=[profile?]  <dev-haskell/network-3.2:=[profile?] )
	!network-uri? ( >=dev-haskell/network-2.5:=[profile?] <dev-haskell/network-2.6:=[profile?] )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.18.1.3
	test? ( >=dev-haskell/aeson-1.4 <dev-haskell/aeson-1.5
		>=dev-haskell/quickcheck-2.11 <dev-haskell/quickcheck-2.14
		>=dev-haskell/tasty-1.2 <dev-haskell/tasty-1.3
		>=dev-haskell/tasty-hunit-0.10 <dev-haskell/tasty-hunit-0.11
		>=dev-haskell/tasty-quickcheck-0.10 <dev-haskell/tasty-quickcheck-0.11
		>=dev-haskell/temporary-1.2 <dev-haskell/temporary-1.4
		>=dev-haskell/unordered-containers-0.2.8.0 <dev-haskell/unordered-containers-0.3
		>=dev-haskell/vector-0.12 <dev-haskell/vector-0.13
		!network-uri? ( dev-haskell/network-uri ) )
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag mtl21 mtl21) \
		$(cabal_flag network-uri use-network-uri)
}
