# Copyright 1999-2020 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=7

# ebuild generated by hackport 0.6.1

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Support for manipulating Haskell source code"
HOMEPAGE="https://hackage.haskell.org/package/haskell-src"
SRC_URI="https://hackage.haskell.org/package/${P}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64"
IUSE=""

RDEPEND=">=dev-haskell/syb-0.7:=[profile?] <dev-haskell/syb-0.8:=[profile?]
	>=dev-lang/ghc-8.8.1:=[profile?]
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.0.0.0
	>=dev-haskell/happy-1.19
"

src_prepare() {
	default

	cabal_chdeps \
		'happy:happy == 1.19.*' 'happy:happy >= 1.19' \
		'base   ^>= 4.13.0.0' 'base   >= 4.13.0.0'
}
