# Copyright 1999-2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header:  $

# ebuild generated by hackport 0.2.13

EAPI="3"

CABAL_FEATURES="bin lib profile haddock hscolour hoogle"
inherit base haskell-cabal

DESCRIPTION="Snap: A Haskell Web Framework: project starter executable and glue code library"
HOMEPAGE="http://snapframework.com/"
SRC_URI="http://hackage.haskell.org/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/aeson-0.4
		=dev-haskell/attoparsec-0.10*
		<dev-haskell/blaze-builder-0.4
		dev-haskell/bytestring-nums
		=dev-haskell/cereal-0.3*
		=dev-haskell/clientsession-0.7*
		=dev-haskell/configurator-0.2*
		=dev-haskell/crypto-4.2*
		=dev-haskell/directory-tree-0.10*
		=dev-haskell/data-lens-2.0*
		=dev-haskell/data-lens-template-2.1*
		=dev-haskell/dlist-0.5*
		=dev-haskell/enumerator-0.4*
		=dev-haskell/hashable-1.1*
		=dev-haskell/heist-0.7*
		>=dev-haskell/hint-0.3
		=dev-haskell/logict-0.5*
		=dev-haskell/monadcatchio-transformers-0.2*
		>=dev-haskell/mtl-2
		<dev-haskell/mwc-random-0.11
		=dev-haskell/pwstore-fast-2.2*
		=dev-haskell/safe-0.3*
		=dev-haskell/skein-0.1*
		=dev-haskell/snap-core-0.7*
		=dev-haskell/snap-server-0.7*
		=dev-haskell/stm-2.2*
		=dev-haskell/syb-0.3*
		=dev-haskell/text-0.11*
		<dev-haskell/time-1.5
		=dev-haskell/transformers-0.2*
		=dev-haskell/unordered-containers-0.1*
		dev-haskell/unix-compat
		=dev-haskell/utf8-string-0.3*
		<dev-haskell/vector-0.10
		<dev-haskell/vector-algorithms-0.6
		=dev-haskell/xmlhtml-0.1*
		dev-haskell/zlib
		>=dev-lang/ghc-7.0.1"
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.8"

PATCHES=("${FILESDIR}/${PN}-0.7-ghc-7.4.patch")

src_prepare() {
	base_src_prepare
	sed -e 's@aeson                     >= 0.4      && < 0.5@aeson                     >= 0.4      \&\& < 0.6@' \
		-i "${S}/${PN}.cabal" || die "Could not loosen dependencies"
}
