#!/sbin/openrc-run
# Copyright 1999-2013 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

PIDFILE="/var/run/keter/keter.pid"

extra_started_commands="reload"
description="Web application deployment manager, focusing on Haskell web frameworks"
description_reload="Reload the keter configuration without losing connections."

depend() {
	need net
	use dns logger netmount
}

check_configuration() {
	if [ ! -e /etc/keter/keter.yaml ] ; then
		eerror "To execute the keter server you need a /etc/keter/keter.yaml configuration"
		eerror "file. In /etc/keter you can find a sample configuration."
		return 1
	fi
}

start() {
	checkpath -d /var/run/keter
	[ "${RC_CMD}" = "restart" ] || check_configuration || return 1
	ebegin "Starting keter"
	/usr/bin/keter /etc/keter/keter.yaml &
	echo $! >"$PIDFILE"
	eend $?
}

stop() {
	[ "${RC_CMD}" != "restart" ] || check_configuration || return 1
	ebegin "Stopping keter"
	read -r pid < $PIDFILE
	rm -f $PIDFILE
	kill $pid || kill -9 $pid
	eend $?
}

reload() {
	check_configuration || return 1
	ebegin "Reloading keter"
	$0 stop
	sleep 3
	$0 start
	eend $?
}
