# Copyright 1999-2024 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.8.5.1

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="GetText runtime library implementation in pure Haskell"
HOMEPAGE="https://hackage.haskell.org/package/haskell-gettext"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64"

RDEPEND=">=dev-haskell/haskell-src-exts-1.18:=[profile?]
	>=dev-haskell/old-locale-1.0:=[profile?]
	>=dev-haskell/parsec-3.1.11:=[profile?]
	>=dev-haskell/text-1.2:=[profile?]
	>=dev-haskell/uniplate-1.6.12:=[profile?]
	>=dev-lang/ghc-9.0.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
"
