# Copyright 1999-2018 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

EAPI=6

# ebuild generated by hackport 0.4.6.9999
#hackport: flags: -developer

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Fast combinator parsing for bytestrings and text"
HOMEPAGE="https://bitbucket.org/blamario/picoparsec"
SRC_URI="https://hackage.haskell.org/package/${P}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/monoid-subclasses-0.4:=[profile?] <dev-haskell/monoid-subclasses-0.5:=[profile?]
	>=dev-haskell/scientific-0.3.1:=[profile?] <dev-haskell/scientific-0.4:=[profile?]
	>=dev-haskell/text-1.1.1.3:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.8
	test? ( >=dev-haskell/quickcheck-2.7
		>=dev-haskell/quickcheck-instances-0.3 <dev-haskell/quickcheck-instances-0.4
		dev-haskell/quickcheck-unicode
		>=dev-haskell/tasty-0.7
		>=dev-haskell/tasty-quickcheck-0.7
		dev-haskell/vector )
"

PATCHES=(
	"${FILESDIR}"/${P}-ghc84.patch
)

src_configure() {
	haskell-cabal_src_configure \
		--flag=-developer
}
