# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.3.1.9999

CABAL_FEATURES="bin lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Generate or process x-www-urlencoded data"
HOMEPAGE="https://github.com/pheaver/urlencoded"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/mtl-1.1:=[profile?]
	>=dev-haskell/network-2.2:=[profile?] <dev-haskell/network-4:=[profile?]
	dev-haskell/network-uri:=[profile?]
	>=dev-haskell/split-0.2:=[profile?] <dev-haskell/split-0.4:=[profile?]
	>=dev-lang/ghc-6.10.4:="
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.6"

src_prepare() {
	cabal_chdeps \
		'split == 0.2.*' 'split >= 0.2 && < 0.4' \
		'network >= 2.2 && < 4' 'network >= 2.2 && < 4, network-uri'
}
