# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.9999

CABAL_FEATURES="lib profile test-suite" # haddock hoogle hscolour, bad markup
inherit haskell-cabal

DESCRIPTION="Making de Bruijn Succ Less"
HOMEPAGE="http://github.com/ekmett/bound/"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/bifunctors-3:=[profile?] <dev-haskell/bifunctors-5:=[profile?]
	>=dev-haskell/binary-0.5:=[profile?] <dev-haskell/binary-0.8:=[profile?]
	>=dev-haskell/bytes-0.4:=[profile?] <dev-haskell/bytes-1:=[profile?]
	>=dev-haskell/cereal-0.3.5.2:=[profile?] <dev-haskell/cereal-0.5:=[profile?]
	>=dev-haskell/comonad-3:=[profile?] <dev-haskell/comonad-5:=[profile?]
	>=dev-haskell/hashable-1.1:=[profile?] <dev-haskell/hashable-1.3:=[profile?]
	>=dev-haskell/hashable-extras-0.1:=[profile?] <dev-haskell/hashable-extras-1:=[profile?]
	>=dev-haskell/prelude-extras-0.3:=[profile?] <dev-haskell/prelude-extras-1:=[profile?]
	>=dev-haskell/profunctors-3.3:=[profile?] <dev-haskell/profunctors-5:=[profile?]
	>=dev-haskell/transformers-0.2:=[profile?] <dev-haskell/transformers-0.4:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.9.2
	test? ( >=dev-haskell/doctest-0.9 <dev-haskell/doctest-0.10
		dev-haskell/prelude-extras
		dev-haskell/transformers
		>=dev-haskell/vector-0.9 <dev-haskell/vector-0.11 )
"
