# Copyright 1999-2023 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.8.4.0.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Unofficial OpenAI client"
HOMEPAGE="https://github.com/agrafix/openai-hs#readme"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64"

RDEPEND="dev-haskell/aeson:=[profile?]
	dev-haskell/casing:=[profile?]
	dev-haskell/cpphs:=[profile?]
	dev-haskell/http-client:=[profile?]
	dev-haskell/http-types:=[profile?]
	>=dev-haskell/openai-servant-0.2.1:=[profile?]
	dev-haskell/servant:=[profile?]
	dev-haskell/servant-auth-client:=[profile?]
	dev-haskell/servant-client:=[profile?]
	dev-haskell/servant-multipart-client:=[profile?]
	dev-haskell/text:=[profile?]
	>=dev-lang/ghc-8.10.6:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.2.1.0
	test? ( dev-haskell/hspec
		dev-haskell/http-client-tls
		dev-haskell/servant-client-core
		dev-haskell/vector )
"
