# Copyright 1999-2013 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.3.2.9999

CABAL_FEATURES="bin lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="A static website compiler library"
HOMEPAGE="http://jaspervdj.be/hakyll"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~x86 ~amd64"
IUSE="+previewServer"

RDEPEND="=app-text/pandoc-1.10*:=[profile?]
		>=dev-haskell/binary-0.5:=[profile?]
		<dev-haskell/binary-0.8:=[profile?]
		=dev-haskell/blaze-html-0.5*:=[profile?]
		>=dev-haskell/blaze-markup-0.5.1:=[profile?]
		<dev-haskell/blaze-markup-0.6:=[profile?]
		>=dev-haskell/citeproc-hs-0.3.2:=[profile?]
		<dev-haskell/citeproc-hs-0.4:=[profile?]
		=dev-haskell/cmdargs-0.10*:=[profile?]
		>=dev-haskell/cryptohash-0.7:=[profile?]
		<dev-haskell/cryptohash-0.9:=[profile?]
		=dev-haskell/deepseq-1.3*:=[profile?]
		>=dev-haskell/http-conduit-1.8:=[profile?]
		<dev-haskell/http-conduit-2.0:=[profile?]
		>=dev-haskell/http-types-0.7:=[profile?] <dev-haskell/http-types-0.9:=[profile?]
		>=dev-haskell/lrucache-1.1.1:=[profile?]
		<dev-haskell/lrucache-1.2:=[profile?]
		>=dev-haskell/mtl-1:=[profile?]
		<dev-haskell/mtl-2.2:=[profile?]
		>=dev-haskell/parsec-3.0:=[profile?]
		<dev-haskell/parsec-3.2:=[profile?]
		=dev-haskell/random-1.0*:=[profile?]
		=dev-haskell/regex-base-0.93*:=[profile?]
		=dev-haskell/regex-tdfa-1.1*:=[profile?]
		>=dev-haskell/snap-core-0.6:=[profile?]
		<dev-haskell/snap-core-0.10:=[profile?]
		>=dev-haskell/snap-server-0.6:=[profile?]
		<dev-haskell/snap-server-0.10:=[profile?]
		>=dev-haskell/tagsoup-0.12.6:=[profile?]
		<dev-haskell/tagsoup-0.13:=[profile?]
		>=dev-haskell/text-0.11:=[profile?]
		<dev-haskell/text-1.12:=[profile?]
		>=dev-lang/ghc-6.12.1:="
DEPEND="${RDEPEND}
		test? ( =dev-haskell/hunit-1.2*
			>=dev-haskell/quickcheck-2.4
			<dev-haskell/quickcheck-2.6
			>=dev-haskell/test-framework-0.4
			<dev-haskell/test-framework-0.9
			>=dev-haskell/test-framework-hunit-0.2
			<dev-haskell/test-framework-hunit-0.4
			>=dev-haskell/test-framework-quickcheck2-0.2
			<dev-haskell/test-framework-quickcheck2-0.4
		)
		>=dev-haskell/cabal-1.8"

src_prepare() {
	cabal_chdeps \
		'binary       >= 0.5    && < 0.7' 'binary       >= 0.5    && < 0.8' \
		'http-conduit >= 1.8    && < 1.9' 'http-conduit >= 1.8    && < 2.0' \
		'http-types   >= 0.7    && < 0.8' 'http-types   >= 0.7    && < 0.9'
}

src_configure() {
	cabal_src_configure \
		$(cabal_flag previewServer previewServer)
}
