# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

EAPI=5

# ebuild generated by hackport 0.4.6.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Object-oriented programming realization using coroutine"
HOMEPAGE="http://hackage.haskell.org/package/coroutine-object"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">dev-haskell/cereal-0.3:=[profile?]
	>=dev-haskell/either-3.1:=[profile?]
	>=dev-haskell/lens-2.5:=[profile?]
	>dev-haskell/mtl-2:=[profile?]
	>=dev-haskell/safecopy-0.6:=[profile?]
	>=dev-haskell/transformers-0.3:=[profile?]
	>=dev-haskell/transformers-free-1.0:=[profile?]
	>dev-haskell/uuid-1.2:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.8
"
