#! /bin/sh

BINNAME_LONG="$(basename $0)"
BINNAME="${BINNAME_LONG%-tc}"

if [ -n "${HELIUM_TEMP}" ]; then
	TEMP="${HELIUM_TEMP}";
else
	TEMP="/tmp/helium-${USER}"	
	if ! [ -d "${TEMP}" ]; then
		mkdir ${TEMP};
	fi;
fi

if [ "${BINNAME_LONG}" = "${BINNAME}" ]; then
	HELIUM_LIBS="/usr/lib/helium/lib";
else
	HELIUM_LIBS="/usr/lib/helium/tclib";
fi

if [ -z "${LVMPATH}" ]; then
	LVMPATH=".:${HELIUM_LIBS}";
else
	LVMPATH="${LVMPATH}:${HELIUM_LIBS}";
fi
export LVMPATH
export TEMP

if [ "${BINNAME}" = "hint" ]; then

	JAVA="$(java-config --java)"
        PROGCALL="${JAVA} -jar -DPATH=${PATH} -DLVMPATH=${LVMPATH} /usr/share/helium/lib/Hint.jar"

else

	PROGCALL="/usr/lib/helium/bin/${BINNAME}"

fi

${PROGCALL} $*
