# Copyright 1999-2023 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.8.4.0

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Orphan Instances for 'Data.Vector'"
HOMEPAGE="https://github.com/ekmett/vector-instances"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64"
IUSE="+hashable"

RDEPEND=">=dev-haskell/comonad-3:=[profile?]
	>=dev-haskell/keys-3:=[profile?]
	>=dev-haskell/pointed-3:=[profile?]
	>=dev-haskell/semigroupoids-3:=[profile?]
	>=dev-haskell/vector-0.12:=[profile?] <dev-haskell/vector-0.14:=[profile?]
	>=dev-lang/ghc-8.8.1:=
	hashable? ( >=dev-haskell/hashable-1.2.5.0:=[profile?] )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.0.0.0
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag hashable hashable)
}
