# Copyright 1999-2020 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=7

# ebuild generated by hackport 0.6.6.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Write bots for Discord in Haskell"
HOMEPAGE="https://github.com/aquarial/discord-haskell"
SRC_URI="https://hackage.haskell.org/package/${P}/${P}.tar.gz"

LICENSE="MIT"
SLOT="0/${PV}"
KEYWORDS="~amd64"
IUSE=""

RDEPEND="dev-haskell/aeson:=[profile?]
	dev-haskell/async:=[profile?]
	dev-haskell/base64-bytestring:=[profile?]
	dev-haskell/data-default:=[profile?]
	~dev-haskell/emoji-0.1.0.2:=[profile?]
	dev-haskell/http-client:=[profile?]
	dev-haskell/iso8601-time:=[profile?]
	dev-haskell/juicypixels:=[profile?]
	dev-haskell/monadrandom:=[profile?]
	dev-haskell/mtl:=[profile?]
	dev-haskell/req:=[profile?]
	dev-haskell/safe-exceptions:=[profile?]
	dev-haskell/text:=[profile?]
	dev-haskell/unliftio:=[profile?]
	dev-haskell/unordered-containers:=[profile?]
	dev-haskell/vector:=[profile?]
	dev-haskell/websockets:=[profile?]
	dev-haskell/wuss:=[profile?]
	>=dev-lang/ghc-7.4.1:=[profile?]
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-2.0
"
