#!/sbin/openrc-run
# Copyright 1999-2022 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

extra_commands="generate"

name="Hoogle search daemon"
description="Haskell API Search daemon"
pidfile="/var/run/hoogle.pid"
command="/usr/bin/hoogle"
command_args="server --port ${HOOGLE_SERVER_PORT} --host ${HOOGLE_SERVER_HOST} ${HOOGLE_SERVER_EXTRA_ARGS}"
command_background="true"
command_user="hoogle:hoogle"
directory="/var/lib/hoogle"
supervisor=supervise-daemon
shell=/bin/sh
su=/bin/su

start_pre() {
	generate
}

generate() {
	ebegin "Generating hoogle database"
	HOOGLE_GENERATE_ARGS:="--local +RTS -N"
	"$su" -c "/usr/libexec/hoogle-generate.bash ${HOOGLE_GENERATE_ARGS}" -s "$shell" - hoogle
	eend $?
}
