# Copyright 1999-2018 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

EAPI=6

# ebuild generated by hackport 0.5.6.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Monad transformers and classes"
HOMEPAGE="https://int-index.github.io/ether/"
SRC_URI="https://hackage.haskell.org/package/${P}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="disable-tup-instances"

RDEPEND=">=dev-haskell/exceptions-0.8:=[profile?]
	>=dev-haskell/mmorph-1.0.4:=[profile?]
	>=dev-haskell/monad-control-1.0.0.4:=[profile?]
	>=dev-haskell/mtl-2.2.1:=[profile?]
	>=dev-haskell/reflection-2.1:=[profile?]
	>=dev-haskell/tagged-0.8.5:=[profile?]
	>=dev-haskell/transformers-base-0.4.4:=[profile?]
	>=dev-haskell/transformers-lift-0.2.0.1:=[profile?]
	>=dev-haskell/writer-cps-mtl-0.1.1.4:=[profile?]
	>=dev-lang/ghc-8.0.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.24.0.0
	test? ( >=dev-haskell/lens-4.14
		>=dev-haskell/quickcheck-2.8
		>=dev-haskell/tasty-0.10
		>=dev-haskell/tasty-quickcheck-0.8 )
"

src_prepare() {
	default

	cabal_chdeps \
		'base >=4.9 && <4.11' 'base >=4.9'
}

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag disable-tup-instances disable-tup-instances)
}
