# Copyright 1999-2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.0.0.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Bindings to the btrfs API"
HOMEPAGE="https://github.com/redneb/hs-btrfs"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64"

RDEPEND=">=dev-lang/ghc-9.6.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.10.1.0
"

src_configure() {
	# examples need to be ported to unix-2.8
	haskell-cabal_src_configure \
		--flag=-examples
}
