# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.3.6.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="SVGFonts"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Fonts from the SVG-Font format"
HOMEPAGE="http://hackage.haskell.org/package/SVGFonts"
SRC_URI="mirror://hackage/packages/archive/${MY_PN}/${PV}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="dev-haskell/attoparsec:=[profile?]
	>=dev-haskell/blaze-markup-0.5:=[profile?]
	>=dev-haskell/blaze-svg-0.3.3:=[profile?]
	<dev-haskell/data-default-class-0.1:=[profile?]
	>=dev-haskell/diagrams-lib-0.7:=[profile?] <dev-haskell/diagrams-lib-1.1:=[profile?]
	dev-haskell/parsec:=[profile?]
	dev-haskell/split:=[profile?]
	dev-haskell/text:=[profile?]
	dev-haskell/tuple:=[profile?]
	dev-haskell/vector:=[profile?]
	dev-haskell/vector-space:=[profile?]
	dev-haskell/xml:=[profile?]
	>=dev-lang/ghc-7.0.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.10.0.0
"

S="${WORKDIR}/${MY_P}"
