# Copyright 1999-2024 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.8.5.1.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Dynamic reconfiguration in Haskell"
HOMEPAGE="https://github.com/willdonnelly/dyre"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64"

RESTRICT="test" # Lib.hs:3:1: error: Could not find module ‘Config.Dyre’

RDEPEND="dev-haskell/executable-path:=[profile?]
	dev-haskell/io-storage:=[profile?]
	dev-haskell/xdg-basedir:=[profile?]
	>=dev-lang/ghc-9.0.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
"
