# Copyright 1999-2023 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.8.1.0.9999

CABAL_HACKAGE_REVISION=1

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="A promoted and singled version of the base library"
HOMEPAGE="https://www.github.com/goldfirere/singletons"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64"

RDEPEND="
	~dev-haskell/singletons-3.0.1:=[profile?]
	>=dev-haskell/singletons-th-3.1:=[profile?] <dev-haskell/singletons-th-3.2:=[profile?]
	>=dev-haskell/text-1.2:=[profile?]
	>=dev-haskell/th-desugar-1.13:=[profile?] <dev-haskell/th-desugar-1.14:=[profile?]
	>=dev-lang/ghc-9.2.4:=[profile?]
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.6.3.0 <dev-haskell/cabal-3.7
	test? ( 
		>=dev-haskell/tasty-1.2
		>=dev-haskell/tasty-golden-2.2
		>=dev-haskell/turtle-1.5
	)
"
