# Copyright 1999-2017 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

EAPI=6

# ebuild generated by hackport 0.5.3.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="A data-type like Either but with an accumulating Applicative"
HOMEPAGE="https://github.com/qfpl/validation"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="+small_base"

RESTRICT=test # missing files

RDEPEND=">=dev-haskell/bifunctors-3.0:=[profile?]
	>=dev-haskell/lens-4.0:=[profile?] <dev-haskell/lens-5:=[profile?]
	>=dev-haskell/mtl-2.0:=[profile?] <dev-haskell/mtl-2.3:=[profile?]
	>=dev-haskell/semigroupoids-4.0:=[profile?]
	>=dev-haskell/semigroups-0.8:=[profile?]
	>=dev-lang/ghc-7.8.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.18.1.3
	test? ( >=dev-haskell/doctest-0.9.7
		>=dev-haskell/quickcheck-2.0 )
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag small_base small_base)
}
