# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=4

# ebuild generated by hackport 0.2.18.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Introduces conduits to channels, and promotes using
conduits concurrently."
HOMEPAGE="https://github.com/wowus/stm-conduit"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="=dev-haskell/conduit-0.5*[profile?]
		>=dev-haskell/resourcet-0.3[profile?]
		<dev-haskell/resourcet-0.5[profile?]
		=dev-haskell/stm-2.4*[profile?]
		=dev-haskell/stm-chans-1.3*[profile?]
		>=dev-haskell/transformers-0.2[profile?]
		<=dev-haskell/transformers-0.4[profile?]
		>=dev-lang/ghc-6.10.1"
DEPEND="${RDEPEND}
		test? ( dev-haskell/hunit
			>=dev-haskell/quickcheck-2
			dev-haskell/test-framework
			dev-haskell/test-framework-hunit
			dev-haskell/test-framework-quickcheck2
		)
		>=dev-haskell/cabal-1.8"
