# Copyright 1999-2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.0.0.9999
#hackport: flags: skiphlinttester:skip-hlint-tester

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="SMT Based Verification: Symbolic Haskell theorem prover using SMT solving"
HOMEPAGE="https://github.com/LeventErkok/sbv"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64"
IUSE="skip-hlint-tester"

# SBVConnections: Unable to locate executable for ABC
RESTRICT=test

RDEPEND=">=dev-haskell/async-2.2.5:=[profile?]
	>=dev-haskell/libbf-0.6.8:=[profile?]
	dev-haskell/quickcheck:=[profile?]
	dev-haskell/random:=[profile?]
	dev-haskell/syb:=[profile?]
	dev-haskell/text:=[profile?]
	dev-haskell/uniplate:=[profile?]
	>=dev-lang/ghc-9.8.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.10.3.0
	test? ( dev-haskell/tasty
		dev-haskell/tasty-golden
		dev-haskell/tasty-hunit
		dev-haskell/tasty-quickcheck
		!skip-hlint-tester? ( dev-haskell/hlint ) )
"
