# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.2.9999

CABAL_FEATURES="bin lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Fast, packed, strict storable arrays with a list interface like ByteString"
HOMEPAGE="http://www.haskell.org/haskellwiki/Storable_Vector"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="buildtests +functorinstance"

RDEPEND="buildtests? ( !functorinstance? ( >=dev-haskell/non-negative-0.1:=[profile?] <dev-haskell/non-negative-0.2:=[profile?]
						>=dev-haskell/quickcheck-1:2=[profile?] <dev-haskell/quickcheck-3:2=[profile?]
						>=dev-haskell/random-1.0:=[profile?] <dev-haskell/random-1.1:=[profile?]
						>=dev-haskell/sample-frame-0.0.1:=[profile?] <dev-haskell/sample-frame-0.1:=[profile?]
						>=dev-haskell/syb-0.1:=[profile?] <dev-haskell/syb-0.5:=[profile?]
						>=dev-haskell/transformers-0.2:=[profile?] <dev-haskell/transformers-0.5:=[profile?]
						>=dev-haskell/unsafe-0.0:=[profile?] <dev-haskell/unsafe-0.1:=[profile?]
						>=dev-haskell/utility-ht-0.0.5:=[profile?] <dev-haskell/utility-ht-0.1:=[profile?]
						>=dev-lang/ghc-7.4.1:= ) )
	!buildtests? ( >=dev-haskell/non-negative-0.1:=[profile?] <dev-haskell/non-negative-0.2:=[profile?]
			>=dev-haskell/quickcheck-1:2=[profile?] <dev-haskell/quickcheck-3:2=[profile?]
			>=dev-haskell/syb-0.1:=[profile?] <dev-haskell/syb-0.5:=[profile?]
			>=dev-haskell/transformers-0.2:=[profile?] <dev-haskell/transformers-0.5:=[profile?]
			>=dev-haskell/unsafe-0.0:=[profile?] <dev-haskell/unsafe-0.1:=[profile?]
			>=dev-haskell/utility-ht-0.0.5:=[profile?] <dev-haskell/utility-ht-0.1:=[profile?]
			>=dev-lang/ghc-7.4.1:= )
"
DEPEND="${RDEPEND}
	buildtests? ( !functorinstance? ( >=dev-haskell/cabal-1.6 ) )
	!buildtests? ( >=dev-haskell/cabal-1.6 )
"

src_prepare() {
	cabal_chdeps \
		'transformers >=0.2 && <0.4' 'transformers >=0.2 && <0.5' \
		'syb >=0.1 && <0.4' 'syb >=0.1 && <0.5'
}

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag buildtests buildtests) \
		$(cabal_flag functorinstance functorinstance)
}
