# Copyright 1999-2022 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.7.1.1.9999

CABAL_FEATURES=""
inherit haskell-cabal

DESCRIPTION="A graphical tool for profiling parallel Haskell programs"
HOMEPAGE="https://www.haskell.org/haskellwiki/ThreadScope"
SRC_URI="https://hackage.haskell.org/package/${P}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64"

RDEPEND="<dev-haskell/cairo-0.14:=
	<dev-haskell/file-embed-0.1:=
	>=dev-haskell/ghc-events-0.13:= <dev-haskell/ghc-events-0.18:=
	<dev-haskell/glib-0.14:=
	>=dev-haskell/gtk-0.12:= <dev-haskell/gtk-0.16:=
	<dev-haskell/pango-0.14:=
	>=dev-haskell/temporary-1.1:= <dev-haskell/temporary-1.4:=
	>=dev-lang/ghc-8.4.3:=[profile?]
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-2.2.0.1
"
