# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

EAPI=5

# ebuild generated by hackport 0.4.5.9999

CABAL_FEATURES="bin"
inherit haskell-cabal

DESCRIPTION="A graphical tool for profiling parallel Haskell programs"
HOMEPAGE="http://www.haskell.org/haskellwiki/ThreadScope"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="dev-haskell/binary:=
	dev-haskell/cairo:=
	>=dev-haskell/ghc-events-0.4.2:=
	dev-haskell/glib:=
	>=dev-haskell/gtk-0.12:2=
	dev-haskell/mtl:=
	dev-haskell/pango:=
	dev-haskell/text:=
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.6
"
