# Copyright 1999-2013 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.3.9999

GTK_MAJ_VER="2"

CABAL_FEATURES="bin"
inherit base haskell-cabal

DESCRIPTION="A graphical tool for profiling parallel Haskell programs."
HOMEPAGE="http://www.haskell.org/haskellwiki/ThreadScope"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=""
DEPEND="${RDEPEND}
		dev-haskell/binary
		>=dev-haskell/cabal-1.6
		>=dev-haskell/cairo-0.12.5.0:0
		>=dev-haskell/deepseq-1.1
		>=dev-haskell/ghc-events-0.4.2
		dev-haskell/glib:0
		>=dev-haskell/gtk-0.12.5.0:${GTK_MAJ_VER}
		dev-haskell/mtl
		dev-haskell/pango:0
		>=dev-lang/ghc-6.10.4"

PATCHES=("${FILESDIR}/${PN}-0.2.2-gtk2hs-0.12.5.0.patch")

src_prepare() {
	base_src_prepare

	# ghc-7.8
	cabal_chdeps \
		'unix >= 2.3 && < 2.7' 'unix >= 2.3'
}
