# Copyright 1999-2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header:	$

# ebuild generated by hackport 0.2.13

EAPI="3"

CABAL_FEATURES="lib profile haddock hscolour"
inherit haskell-cabal

DESCRIPTION="Static file serving subsite for Yesod Web Framework."
HOMEPAGE="http://www.yesodweb.com/"
SRC_URI="http://hackage.haskell.org/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE="test"

RDEPEND="=dev-haskell/base64-bytestring-0.1*
		=dev-haskell/cereal-0.3*
		<dev-haskell/file-embed-0.5
		=dev-haskell/http-types-0.6*
		=dev-haskell/puremd5-2.1*
		<dev-haskell/text-1.0
		=dev-haskell/transformers-0.2*
		<dev-haskell/unix-compat-0.4
		=dev-haskell/wai-0.4*
		=dev-haskell/wai-app-static-0.3*
		=dev-haskell/yesod-core-0.9*
		>=dev-lang/ghc-6.12.1"
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.8
		test? ( >=dev-haskell/hspec-0.8
				dev-haskell/hunit
				dev-haskell/wai-test
				dev-haskell/zlib
		)"

src_prepare() {
	cp -r "${FILESDIR}/${PN}-0.3.0.1/"* "${S}"/ || die

	sed -e 's@containers                >= 0.4@containers                >= 0.3@' \
		-e 's@unix-compat               >= 0.2      && < 0.3@unix-compat               >= 0.2      \&\& < 0.4@' \
		-e 's@hspec >= 0.8   && < 0.9@hspec >= 0.8   \&\& < 0.10@' \
		-i "${S}/${PN}.cabal" || die "Could not loosen dependencies"
}

src_configure() {
	cabal_src_configure $(use_enable test tests)
}
