# Copyright 1999-2020 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=7

# ebuild generated by hackport 0.6.3

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="CAES Language for Synchronous Hardware - Prelude library"
HOMEPAGE="http://www.clash-lang.org/"
SRC_URI="https://hackage.haskell.org/package/${P}/${P}.tar.gz"

LICENSE="BSD-2"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="+benchmarks +doctests multiple-hidden super-strict +unittests"

RESTRICT=test # Ambiguous module name ‘Data.Constraint’: constraints-0.11.2 constraints-deriving-1.1.1.0

RDEPEND=">=dev-haskell/bifunctors-5.4.0:=[profile?] <dev-haskell/bifunctors-6.0:=[profile?]
	>=dev-haskell/constraints-0.9:=[profile?] <dev-haskell/constraints-1.0:=[profile?]
	>=dev-haskell/data-binary-ieee754-0.4.4:=[profile?] <dev-haskell/data-binary-ieee754-0.6:=[profile?]
	>=dev-haskell/data-default-class-0.1.2:=[profile?] <dev-haskell/data-default-class-0.2:=[profile?]
	>=dev-haskell/ghc-typelits-extra-0.3.1:=[profile?] <dev-haskell/ghc-typelits-extra-0.4:=[profile?]
	>=dev-haskell/ghc-typelits-knownnat-0.6:=[profile?] <dev-haskell/ghc-typelits-knownnat-0.8:=[profile?]
	>=dev-haskell/ghc-typelits-natnormalise-0.6:=[profile?] <dev-haskell/ghc-typelits-natnormalise-0.8:=[profile?]
	>=dev-haskell/half-0.2.2.3:=[profile?] <dev-haskell/half-1.0:=[profile?]
	>=dev-haskell/hashable-1.2.1.0:=[profile?] <dev-haskell/hashable-1.4:=[profile?]
	>=dev-haskell/lens-4.9:=[profile?] <dev-haskell/lens-4.19:=[profile?]
	>=dev-haskell/quickcheck-2.7:2=[profile?] <dev-haskell/quickcheck-2.14:2=[profile?]
	>=dev-haskell/reflection-2:=[profile?] <dev-haskell/reflection-2.2:=[profile?]
	>=dev-haskell/singletons-1.0:=[profile?] <dev-haskell/singletons-3.0:=[profile?]
	>=dev-haskell/text-0.11.3.1:=[profile?] <dev-haskell/text-1.3:=[profile?]
	>=dev-haskell/th-lift-0.7.0:=[profile?] <dev-haskell/th-lift-0.9:=[profile?]
	>=dev-haskell/th-orphans-0.13.1:=[profile?] <dev-haskell/th-orphans-1.0:=[profile?]
	>=dev-haskell/type-errors-0.2.0.0:=[profile?] <dev-haskell/type-errors-0.3:=[profile?]
	>=dev-haskell/vector-0.11:=[profile?] <dev-haskell/vector-1.0:=[profile?]
	>=dev-lang/ghc-8.2.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-2.0.0.2
	doctests? ( unittests? ( test? ( >=dev-haskell/doctest-0.9.1 <dev-haskell/doctest-0.17
						>=dev-haskell/hint-0.7 <dev-haskell/hint-0.10
						>=dev-haskell/tasty-1.2 <dev-haskell/tasty-1.3
						dev-haskell/tasty-hunit ) )
			!unittests? ( test? ( >=dev-haskell/doctest-0.9.1 <dev-haskell/doctest-0.17 ) ) )
	!doctests? ( test? ( unittests? ( >=dev-haskell/hint-0.7 <dev-haskell/hint-0.10
						>=dev-haskell/tasty-1.2 <dev-haskell/tasty-1.3
						dev-haskell/tasty-hunit ) ) )
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag benchmarks benchmarks) \
		$(cabal_flag doctests doctests) \
		$(cabal_flag multiple-hidden multiple-hidden) \
		$(cabal_flag super-strict super-strict) \
		$(cabal_flag unittests unittests)
}
