# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=4

# ebuild generated by hackport 0.2.18.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit base haskell-cabal

DESCRIPTION="An (x)html templating system"
HOMEPAGE="http://snapframework.com/"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="=dev-haskell/aeson-0.6*[profile?]
		=dev-haskell/attoparsec-0.10*[profile?]
		>=dev-haskell/blaze-builder-0.2[profile?]
		<dev-haskell/blaze-builder-0.4[profile?]
		>=dev-haskell/blaze-html-0.4[profile?]
		<dev-haskell/blaze-html-0.6[profile?]
		dev-haskell/directory-tree[profile?]
		>=dev-haskell/monadcatchio-transformers-0.2.1[profile?]
		<dev-haskell/monadcatchio-transformers-0.4[profile?]
		>=dev-haskell/mtl-2.0[profile?]
		<dev-haskell/mtl-2.2[profile?]
		dev-haskell/random[profile?]
		>=dev-haskell/text-0.10[profile?]
		<dev-haskell/text-0.12[profile?]
		>=dev-haskell/time-1.1[profile?]
		<dev-haskell/time-1.5[profile?]
		dev-haskell/transformers[profile?]
		>=dev-haskell/unordered-containers-0.1.4[profile?]
		<dev-haskell/unordered-containers-0.3[profile?]
		>=dev-haskell/vector-0.9[profile?]
		<dev-haskell/vector-0.11[profile?]
		>=dev-haskell/xmlhtml-0.1.6[profile?]
		<dev-haskell/xmlhtml-0.3[profile?]
		>=dev-lang/ghc-6.10.1"
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.6"

PATCHES=("${FILESDIR}/${PN}-0.8.2-ghc-7.6.patch")
