# Copyright 1999-2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header:  $

# ebuild generated by hackport 0.2.13

EAPI="3"

CABAL_FEATURES="lib profile haddock hscolour"
inherit haskell-cabal

DESCRIPTION="A Haskell library for writing FastCGI programs"
HOMEPAGE="http://hackage.haskell.org/package/fastcgi"
SRC_URI="http://hackage.haskell.org/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/cgi-3000.0.0
		>=dev-lang/ghc-6.12.1
		dev-libs/fcgi"
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.2.0"
