# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

EAPI=5

# ebuild generated by hackport 0.4.6.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Simple interface for shell scripting in Haskell"
HOMEPAGE="https://github.com/valderman/shellmate"
SRC_URI="https://hackage.haskell.org/package/${P}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="+download-extras"

RDEPEND=">=dev-haskell/http-4000.2:=[profile?]
	>=dev-haskell/network-uri-2.6:=[profile?] <dev-haskell/network-uri-2.7:=[profile?]
	>=dev-haskell/temporary-1.1:=[profile?] <dev-haskell/temporary-1.3:=[profile?]
	>=dev-haskell/transformers-0.3:=[profile?]
	>=dev-lang/ghc-7.8.2:=
	download-extras? ( >=dev-haskell/feed-0.3:=[profile?] <dev-haskell/feed-0.4:=[profile?]
				>=dev-haskell/tagsoup-0.13:=[profile?] <dev-haskell/tagsoup-0.14:=[profile?]
				>=dev-haskell/xml-1.3:=[profile?] <dev-haskell/xml-1.4:=[profile?] )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.18.1.3
"

src_prepare() {
	cabal_chdeps \
		'HTTP         >=4000.2 && <4000.3' 'HTTP         >=4000.2' \
		'transformers >=0.3    && <0.5' 'transformers >=0.3'
}

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag download-extras download-extras)
}
