# Copyright 1999-2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.0.0.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="extend happstack-server with https:// support (TLS/SSL)"
HOMEPAGE="https://www.happstack.com/"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64"

RDEPEND=">=dev-haskell/extensible-exceptions-0.1:=[profile?] <dev-haskell/extensible-exceptions-0.2:=[profile?]
	>=dev-haskell/happstack-server-6.6.4:=[profile?] <dev-haskell/happstack-server-7.10:=[profile?]
	>=dev-haskell/hslogger-1.1:=[profile?] <dev-haskell/hslogger-1.4:=[profile?]
	>=dev-haskell/hsopenssl-0.10:=[profile?] <dev-haskell/hsopenssl-0.12:=[profile?]
	>dev-haskell/network-3.0.0:=[profile?] <dev-haskell/network-3.3:=[profile?]
	>=dev-haskell/sendfile-0.7:=[profile?] <dev-haskell/sendfile-0.8:=[profile?]
	>=dev-lang/ghc-9.0.2:=
	dev-libs/openssl
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
"
