# Copyright 1999-2013 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.3.2.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit base haskell-cabal

DESCRIPTION="Categories"
HOMEPAGE="http://github.com/ekmett/categories"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="optimize"

RDEPEND=">=dev-haskell/void-0.5.4.2:=[profile?]
	>=dev-lang/ghc-6.10.4:="
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.10"

PATCHES=("${FILESDIR}"/${P}-ghc-7.8.patch)

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag optimize optimize)
}
