#!/bin/bash

cd projects/lambdaman
ghc --make -o lambdaman -O -no-user-package-conf -package SHA -Wall Main.hs
err=$?
cd ../..
if [[ -f projects/lambdaman/lambdaman ]] ; then
  if [[ "$err" -ne "0" ]] ; then
    echo
    echo "compiling new lambdaman failed, using old executable"
    echo
  fi

  projects/lambdaman/lambdaman

else
  echo
  echo Please fix above errors and try again.
fi
