#!/bin/bash

cd projects/lambdaman
ghc --make Main.hs \
    -o lambdaman \
    \
    -O2 -Wall \
    \
    -hide-all-packages \
        -package SHA \
        -package base \
        -package process \
        -package filepath \
        -package bytestring \
        -package unix \
        -package directory
err=$?
cd ../..
if [[ -f projects/lambdaman/lambdaman ]] ; then
  if [[ "$err" -ne "0" ]] ; then
    echo
    echo "compiling new lambdaman failed, using old executable"
    echo
  fi

  projects/lambdaman/lambdaman

else
  echo
  echo Please fix above errors and try again.
fi
