# Copyright 1999-2017 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

EAPI=6

# ebuild generated by hackport 0.5.1.9999

CABAL_FEATURES=""
inherit haskell-cabal

DESCRIPTION="query tools for the local cabal database"
HOMEPAGE="https://github.com/vincenthz/cabal-db"
SRC_URI="https://hackage.haskell.org/package/${P}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="dev-haskell/ansi-wl-pprint:=
	dev-haskell/cabal:=
	dev-haskell/mtl:=
	>=dev-haskell/optparse-applicative-0.11:=
	>=dev-haskell/tar-0.4.0:=
	dev-haskell/utf8-string:=
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.8
"

PATCHES=("${FILESDIR}"/${P}-oa-0.13.patch)
