# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.3.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Cairo backend for diagrams drawing EDSL"
HOMEPAGE="http://projects.haskell.org/diagrams"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/cairo-0.10.1:=[profile?]
		<dev-haskell/cairo-0.13:=[profile?]
		>=dev-haskell/cmdargs-0.6:=[profile?]
		<dev-haskell/cmdargs-0.10:=[profile?]
		=dev-haskell/diagrams-core-0.5*:=[profile?]
		=dev-haskell/diagrams-lib-0.5*:=[profile?]
		>=dev-haskell/gtk-0.12.0:=[profile?]
		<dev-haskell/gtk-0.13.0:=[profile?]
		>=dev-haskell/mtl-2.0:=[profile?]
		<dev-haskell/mtl-2.2:=[profile?]
		>=dev-haskell/split-0.1.2:=[profile?]
		<dev-haskell/split-0.2:=[profile?]
		>=dev-lang/ghc-6.12.1:="
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.6"
