# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.3.6.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Turn Data.Serialize Gets and Puts into Sources, Sinks, and Conduits"
HOMEPAGE="https://github.com/litherum/cereal-conduit"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/cereal-0.4.0.0:=[profile?] <dev-haskell/cereal-0.5:=[profile?]
	>=dev-haskell/conduit-1.0.0:=[profile?] <dev-haskell/conduit-1.1:=[profile?]
	>=dev-haskell/transformers-0.2.0.0:=[profile?]
	>=dev-lang/ghc-6.10.4:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.8
	test? ( dev-haskell/hunit
		dev-haskell/mtl
		dev-haskell/resourcet )
"
