# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.3.6.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="High level, generic library for interrogative user interfaces"
HOMEPAGE="http://hackage.haskell.org/package/wizards"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/control-monad-free-0.5:=[profile?] <dev-haskell/control-monad-free-0.7:=[profile?]
	>=dev-haskell/haskeline-0.6:=[profile?] <dev-haskell/haskeline-0.8:=[profile?]
	>=dev-haskell/mtl-2.0:=[profile?] <dev-haskell/mtl-2.3:=[profile?]
	>=dev-haskell/transformers-0.1:=[profile?] <dev-haskell/transformers-0.5:=[profile?]
	>=dev-lang/ghc-7.0.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.10.0.0
"
src_prepare() {
	cabal_chdeps \
		'mtl >= 2.0 && < 2.2, transformers >= 0.1 && < 0.4' \
		'mtl >= 2.0 && < 2.3, transformers >= 0.1 && < 0.5' \
		'control-monad-free ==0.5.*' 'control-monad-free >= 0.5 && < 0.7'
}
