# Copyright 1999-2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header:  $

# ebuild generated by hackport 0.2.13

EAPI="3"

CABAL_FEATURES="lib profile haddock hscolour"
inherit haskell-cabal

DESCRIPTION="Low-level D-Bus protocol implementation"
HOMEPAGE="https://john-millikin.com/software/dbus-core/"
SRC_URI="http://hackage.haskell.org/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="GPL-3"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/binary-0.4
		<dev-haskell/binary-0.6
		>=dev-haskell/data-binary-ieee754-0.3
		<dev-haskell/data-binary-ieee754-0.5
		=dev-haskell/libxml-sax-0.7*
		>=dev-haskell/network-2.2
		<dev-haskell/network-2.4
		>=dev-haskell/parsec-2.0
		<dev-haskell/parsec-3.2
		>=dev-haskell/text-0.11.1.5
		<dev-haskell/text-0.12
		=dev-haskell/vector-0.7*
		=dev-haskell/xml-types-0.3*
		>=dev-lang/ghc-6.10.1"
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.6"
