# Copyright 1999-2020 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=7

# ebuild generated by hackport 0.6.7.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="product-profunctors haskell library"
HOMEPAGE="https://github.com/tomjaguarpaw/product-profunctors"
SRC_URI="https://hackage.haskell.org/package/${P}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/bifunctors-5.4:=[profile?] <dev-haskell/bifunctors-6.0:=[profile?]
	>=dev-haskell/contravariant-0.4:=[profile?] <dev-haskell/contravariant-1.6:=[profile?]
	>=dev-haskell/profunctors-5:=[profile?] <dev-haskell/profunctors-5.7:=[profile?]
	>=dev-haskell/tagged-0.0:=[profile?] <dev-haskell/tagged-1:=[profile?]
	>=dev-lang/ghc-7.8.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.18.1.3
"
