# Copyright 1999-2024 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.8.5.1.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Generic Programming using True Sums of Products"
HOMEPAGE="https://hackage.haskell.org/package/generics-sop"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64"

RDEPEND=">=dev-haskell/sop-core-0.5.0:=[profile?] <dev-haskell/sop-core-0.5.1:=[profile?]
	>=dev-haskell/th-abstraction-0.6:=[profile?] <dev-haskell/th-abstraction-0.7:=[profile?]
	>=dev-lang/ghc-9.0.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
"
