# Copyright 1999-2013 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.3.2.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit git-2 haskell-cabal

DESCRIPTION="Lastfm API interface"
HOMEPAGE="http://hackage.haskell.org/package/liblastfm"
EGIT_REPO_URI="git://github.com/supki/liblastfm.git"

LICENSE="MIT"
SLOT="0/${PV}"
IUSE=""

RDEPEND="dev-haskell/aeson:=[profile?]
		dev-haskell/cereal:=[profile?]
		dev-haskell/crypto-api:=[profile?]
		>=dev-haskell/http-conduit-1.9:=[profile?]
		dev-haskell/http-types:=[profile?]
		dev-haskell/network:=[profile?]
		dev-haskell/puremd5:=[profile?]
		dev-haskell/text:=[profile?]
		>=dev-lang/ghc-7.6.1:="
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.9.2
		test? ( >=dev-haskell/attoparsec-0.10
			dev-haskell/hunit
			dev-haskell/test-framework
			dev-haskell/test-framework-hunit
		)"

RESTRICT=test # designed to fail :]
