# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.5.5.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

MY_PN="TCache"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="A Transactional cache with user-defined persistence"
HOMEPAGE="https://hackage.haskell.org/package/TCache"
SRC_URI="https://hackage.haskell.org/package/${MY_P}/${MY_P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64"
IUSE=""

RDEPEND="dev-haskell/hashtables:=[profile?]
	dev-haskell/mtl:=[profile?]
	>=dev-haskell/old-time-1.0:=[profile?]
	>=dev-haskell/refserialize-0.4.0:=[profile?]
	dev-haskell/stm:=[profile?]
	dev-haskell/text:=[profile?]
	>=dev-lang/ghc-7.4.1:=[profile?]
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.6
"

S="${WORKDIR}/${MY_P}"
