# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.3.1.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="IP Routing Table"
HOMEPAGE="http://www.mew.org/~kazu/proj/iproute/"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="dev-haskell/appar:=[profile?]
		dev-haskell/byteorder:=[profile?]
		dev-haskell/network:=[profile?]
		>=dev-lang/ghc-6.10.4:="
DEPEND="${RDEPEND}
		test? ( >=dev-haskell/doctest-0.9.3
			dev-haskell/hspec
			dev-haskell/quickcheck
			dev-haskell/safe
		)
		>=dev-haskell/cabal-1.10"

src_prepare() {
	cabal_chdeps \
		'Safe' 'safe'
}
