# Copyright 1999-2018 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

EAPI=6

# ebuild generated by hackport 0.5.5

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="automatical derivation of querying functions for servant webservices"
HOMEPAGE="http://haskell-servant.readthedocs.org/"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/aeson-1.2.3.0:=[profile?] <dev-haskell/aeson-1.4:=[profile?]
	>=dev-haskell/attoparsec-0.13.2.0:=[profile?] <dev-haskell/attoparsec-0.14:=[profile?]
	>=dev-haskell/base-compat-0.9.3:=[profile?] <dev-haskell/base-compat-0.11:=[profile?]
	>=dev-haskell/exceptions-0.8.3:=[profile?] <dev-haskell/exceptions-0.11:=[profile?]
	>=dev-haskell/http-client-0.5.7.1:=[profile?] <dev-haskell/http-client-0.6:=[profile?]
	>=dev-haskell/http-client-tls-0.3.5.1:=[profile?] <dev-haskell/http-client-tls-0.4:=[profile?]
	>=dev-haskell/http-media-0.7.0:=[profile?] <dev-haskell/http-media-0.8:=[profile?]
	>=dev-haskell/http-types-0.12:=[profile?] <dev-haskell/http-types-0.13:=[profile?]
	>=dev-haskell/monad-control-1.0.0.4:=[profile?] <dev-haskell/monad-control-1.1:=[profile?]
	>=dev-haskell/mtl-2.1:=[profile?] <dev-haskell/mtl-2.3:=[profile?]
	>=dev-haskell/semigroupoids-5.2.1:=[profile?] <dev-haskell/semigroupoids-5.3:=[profile?]
	>=dev-haskell/semigroups-0.18.3:=[profile?] <dev-haskell/semigroups-0.19:=[profile?]
	>=dev-haskell/servant-client-core-0.13:=[profile?] <dev-haskell/servant-client-core-0.14:=[profile?]
	>=dev-haskell/stm-2.4.4.1:=[profile?] <dev-haskell/stm-2.5:=[profile?]
	>=dev-haskell/text-1.2.3.0:=[profile?] <dev-haskell/text-1.3:=[profile?]
	>=dev-haskell/transformers-base-0.4.4:=[profile?] <dev-haskell/transformers-base-0.5:=[profile?]
	>=dev-haskell/transformers-compat-0.5.1:=[profile?] <dev-haskell/transformers-compat-0.7:=[profile?]
	>=dev-lang/ghc-7.8.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.18.1.3
	test? ( >=dev-haskell/generics-sop-0.3.1.0 <dev-haskell/generics-sop-0.4
		>=dev-haskell/hspec-2.4.4 <dev-haskell/hspec-2.6
		dev-haskell/http-api-data
		>=dev-haskell/hunit-1.6 <dev-haskell/hunit-1.7
		>=dev-haskell/network-2.6.3.2 <dev-haskell/network-2.7
		>=dev-haskell/quickcheck-2.10.1 <dev-haskell/quickcheck-2.12
		>=dev-haskell/servant-0.13 <dev-haskell/servant-0.14
		>=dev-haskell/servant-server-0.13 <dev-haskell/servant-server-0.14
		dev-haskell/wai
		dev-haskell/warp )
"
