# Copyright 1999-2020 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=7

# ebuild generated by hackport 0.6.7.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="A type-safe template engine for working with front end development tools"
HOMEPAGE="https://github.com/arowM/heterocephalus#readme"
SRC_URI="https://hackage.haskell.org/package/${P}/${P}.tar.gz"

LICENSE="MIT"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/blaze-html-0.9:=[profile?]
	>=dev-haskell/blaze-markup-0.8:=[profile?]
	>=dev-haskell/dlist-0.8:=[profile?]
	>=dev-haskell/mtl-2.2:=[profile?]
	>=dev-haskell/parsec-3.1:=[profile?]
	>=dev-haskell/shakespeare-2.0:=[profile?]
	>=dev-haskell/text-1.2:=[profile?]
	>=dev-lang/ghc-8.2.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-2.0.0.2
	test? ( >=dev-haskell/doctest-0.10
		dev-haskell/glob )
"
