# Copyright 1999-2023 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.8.2.0

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="A type-safe template engine for working with front end development tools"
HOMEPAGE="https://github.com/arowM/heterocephalus#readme"
SRC_URI="https://hackage.haskell.org/package/${P}/${P}.tar.gz"

LICENSE="MIT"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"

RDEPEND=">=dev-haskell/blaze-html-0.9.1.2:=[profile?]
	>=dev-haskell/blaze-markup-0.8.2.8:=[profile?]
	>=dev-haskell/dlist-1.0:=[profile?]
	>=dev-haskell/parsec-3.1.14.0:=[profile?]
	>=dev-haskell/shakespeare-2.0.26:=[profile?]
	>=dev-haskell/template-haskell-compat-v0208-0.1.7:=[profile?]
	>=dev-haskell/text-1.2.4.1:=[profile?]
	>=dev-lang/ghc-9.0.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
	test? ( >=dev-haskell/doctest-0.10
		dev-haskell/glob )
"
