# Copyright 1999-2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.0.0.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="EXIF handling library in pure Haskell"
HOMEPAGE="https://github.com/emmanueltouzery/hsexif"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64"
IUSE="+iconv"
RESTRICT="test" #files are missing from the tarball

CABAL_CHDEPS=(
	'bytestring >=0.10 && <0.12' 'bytestring >= 0.10'
	)

RDEPEND=">=dev-haskell/text-0.9:=[profile?]
	>=dev-lang/ghc-9.0.2:=
	iconv? ( >=dev-haskell/iconv-0.4:=[profile?] <dev-haskell/iconv-0.5:=[profile?] )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
	test? ( dev-haskell/hspec
		>=dev-haskell/hunit-1.2 <dev-haskell/hunit-1.7 )
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag iconv iconv)
}
