# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

# ebuild generated by hackport 0.2.14

EAPI="4"

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Kan extensions, the Yoneda lemma, and (co)density (co)monads"
HOMEPAGE="http://github.com/ekmett/kan-extensions/"
SRC_URI="http://hackage.haskell.org/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/adjunctions-2.0.5
		<dev-haskell/adjunctions-2.1
		>=dev-haskell/comonad-1.1.1.1
		<dev-haskell/comonad-1.2
		>=dev-haskell/comonad-transformers-2.0.3
		<dev-haskell/comonad-transformers-2.1
		>=dev-haskell/comonads-fd-2.0.2.1
		<dev-haskell/comonads-fd-2.1
		>=dev-haskell/contravariant-0.1.2
		<dev-haskell/contravariant-0.2
		=dev-haskell/distributive-0.2*
		>=dev-haskell/free-2.0.3
		<dev-haskell/free-2.1
		>=dev-haskell/keys-2.1.2
		<dev-haskell/keys-2.2
		>=dev-haskell/mtl-2.0.1.0
		<dev-haskell/mtl-2.1
		>=dev-haskell/representable-functors-2.1.2
		<dev-haskell/representable-functors-2.2
		>=dev-haskell/semigroupoids-1.2.6.1
		<dev-haskell/semigroupoids-1.3
		=dev-haskell/speculation-1.4*
		=dev-haskell/transformers-0.2*
		>=dev-lang/ghc-7.0.1"
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.6"
