# Copyright 1999-2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.0.0.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="A Prolog interpreter written in Haskell"
HOMEPAGE="https://hackage.haskell.org/package/prolog"

LICENSE="public-domain"
SLOT="0/${PV}"
KEYWORDS="~amd64"

PATCHES=(
	"${FILESDIR}/${PN}-0.3.2-fix-ghc-9.patch"
	"${FILESDIR}/${PN}-0.3.2-fix-mtl-2_3.patch"
)

RDEPEND=">=dev-haskell/parsec-3.1.1:=[profile?]
	>=dev-haskell/syb-0.3:=[profile?]
	>=dev-haskell/th-lift-0.5.3:=[profile?]
	>=dev-lang/ghc-9.0.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
"
