# Copyright 1999-2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.0.0

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="An opinionated formatter for Nix"
HOMEPAGE="https://github.com/NixOS/nixfmt"

LICENSE="MPL-2.0"
SLOT="0/${PV}"
KEYWORDS="~amd64"

CABAL_CHDEPS=('base             >= 4.12.0 && < 4.19' 'base >= 4.12 && < 4.22')

RDEPEND=">=dev-haskell/cmdargs-0.10.20:=[profile?] <dev-haskell/cmdargs-0.11:=[profile?]
	>=dev-haskell/megaparsec-9.0.1:=[profile?] <dev-haskell/megaparsec-9.6:=[profile?]
	>=dev-haskell/parser-combinators-1.0.3:=[profile?] <dev-haskell/parser-combinators-1.4:=[profile?]
	>=dev-haskell/safe-exceptions-0.1.7:=[profile?] <dev-haskell/safe-exceptions-0.2:=[profile?]
	>=dev-haskell/scientific-0.3.0:=[profile?] <dev-haskell/scientific-0.4.0:=[profile?]
	>=dev-haskell/text-1.2.3:=[profile?] <dev-haskell/text-2.2:=[profile?]
	>=dev-lang/ghc-9.0.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
"
