# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.3.2.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Internet Message Parsers"
HOMEPAGE="https://github.com/peti/hsemail"
SRC_URI="https://hackage.haskell.org/package/${P}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64"

RESTRICT=test # multiple packages: parsec-3.1.13.0 parsec1-1.0.0.6

RDEPEND="dev-haskell/mtl:=[profile?]
		dev-haskell/old-time:=[profile?]
		dev-haskell/parsec:=[profile?]
		>=dev-lang/ghc-6.10.4:="
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.8
		test? ( dev-haskell/doctest
			dev-haskell/hspec
		)"

PATCHES=("${FILESDIR}"/${PN}-1.7.5-test-only-mtl.patch)
