# Copyright 1999-2024 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.8.5.1.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Standard spec's for GenValidity instances"
HOMEPAGE="https://github.com/NorfairKing/validity#readme"

LICENSE="MIT"
SLOT="0/${PV}"
KEYWORDS="~amd64"

RDEPEND=">=dev-haskell/genvalidity-1.0:=[profile?]
	>=dev-haskell/genvalidity-property-0.5:=[profile?]
	dev-haskell/hspec:=[profile?]
	>=dev-haskell/hspec-core-2.5.0:=[profile?]
	dev-haskell/quickcheck:=[profile?]
	>=dev-haskell/validity-0.5:=[profile?]
	>=dev-lang/ghc-9.0.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
"
