# Copyright 1999-2013 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.3.3

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Linear algebra and numerical computation"
HOMEPAGE="https://github.com/albertoruiz/hmatrix"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="GPL-2"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="+dd debugfpu debugnan finit mkl unsafe"

RDEPEND="dev-haskell/binary:=[profile?]
	dev-haskell/deepseq:=[profile?]
	dev-haskell/random:=[profile?]
	dev-haskell/storable-complex:=[profile?]
	>=dev-haskell/vector-0.8:=[profile?]
	>=dev-lang/ghc-6.10.4:=
	mkl? ( sci-libs/gsl
		sci-libs/mkl
		virtual/lapack )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.8
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag dd dd) \
		$(cabal_flag debugfpu debugfpu) \
		$(cabal_flag debugnan debugnan) \
		$(cabal_flag finit finit) \
		$(cabal_flag mkl mkl) \
		$(cabal_flag unsafe unsafe)
}
