# Copyright 1999-2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.0.0.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Detect dead code"
HOMEPAGE="https://github.com/ocharles/weeder#readme"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64"

PATCHES=(
	"${FILESDIR}"/${P}-test-fix.patch
	)

RDEPEND=">=dev-haskell/algebraic-graphs-0.7:=[profile?] <dev-haskell/algebraic-graphs-0.8:=[profile?]
	>=dev-haskell/async-2.2.0:=[profile?] <dev-haskell/async-2.3:=[profile?]
	>=dev-haskell/generic-lens-2.2.0.0:=[profile?] <dev-haskell/generic-lens-2.3:=[profile?]
	>=dev-haskell/parallel-3.2.0.0:=[profile?] <dev-haskell/parallel-3.3:=[profile?]
	>=dev-haskell/toml-reader-0.2.0.0:=[profile?] <dev-haskell/toml-reader-0.3:=[profile?]
	>=dev-lang/ghc-9.4.5:=
	>=dev-haskell/glob-0.9:=[profile?] <dev-haskell/glob-0.11:=[profile?]
	>=dev-haskell/lens-5.1:=[profile?] <dev-haskell/lens-5.4:=[profile?]
	>=dev-haskell/optparse-applicative-0.14.3.0:=[profile?] <dev-haskell/optparse-applicative-0.19:=[profile?]
	>=dev-haskell/regex-tdfa-1.2.0.0:=[profile?] <dev-haskell/regex-tdfa-1.4:=[profile?]
	>=dev-haskell/text-2.0.1:=[profile?] <dev-haskell/text-2.2:=[profile?]
	>=dev-lang/ghc-9.4:=[profile?] <dev-lang/ghc-9.9:=[profile?]
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.8.1.0
	test? ( dev-haskell/aeson
		dev-haskell/hspec-expectations
		dev-haskell/tasty
		dev-haskell/tasty-golden
		dev-haskell/tasty-hunit-compat
		dev-haskell/text
		dev-lang/ghc )
"
