# Copyright 1999-2024 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.8.5.1.9999

CABAL_HACKAGE_REVISION=1

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Haskell bindings to the PCG random number generator"
HOMEPAGE="https://github.com/cchalmers/pcg-random"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64"

GHC_BOOTSTRAP_PACKAGES=(
	cabal-doctest
)

RDEPEND="
	dev-haskell/entropy:=[profile?]
	>=dev-haskell/primitive-0.7:=[profile?] <dev-haskell/primitive-0.10:=[profile?]
	>=dev-haskell/random-1.2:=[profile?] <dev-haskell/random-2.0:=[profile?]
	>=dev-lang/ghc-9.0.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0 <dev-haskell/cabal-4.0
	>=dev-haskell/cabal-doctest-1 <dev-haskell/cabal-doctest-1.1
	test? (
		dev-haskell/doctest
	)
"
