# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="A framework for generating singleton types"
HOMEPAGE="http://www.cis.upenn.edu/~eir/packages/singletons"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/mtl-2.1.1:=[profile?]
	>=dev-haskell/th-desugar-1.4:=[profile?]
	>=dev-lang/ghc-7.8.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.18.1.3
	test? ( dev-haskell/constraints
		>=dev-haskell/tasty-0.6
		>=dev-haskell/tasty-golden-2.2 )
"

src_prepare() {
	# https://github.com/gentoo-haskell/gentoo-haskell/pull/360
	# https://ghc.haskell.org/trac/ghc/ticket/9160
	[[ $(ghc-version) == 7.8.* ]] && replace-hcflags -O[2-9] -O1
}
