# Copyright 1999-2020 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=7

# ebuild generated by hackport 0.6.7.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="A framework for generating singleton types"
HOMEPAGE="http://www.github.com/goldfirere/singletons"
SRC_URI="https://hackage.haskell.org/package/${P}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/mtl-2.2.1:=[profile?]
	>=dev-haskell/syb-0.4:=[profile?]
	>=dev-haskell/text-1.2:=[profile?]
	>=dev-haskell/th-desugar-1.11:=[profile?] <dev-haskell/th-desugar-1.12:=[profile?]
	>=dev-lang/ghc-8.10.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.2.0.0 <dev-haskell/cabal-3.3
	test? ( >=dev-haskell/tasty-1.2
		>=dev-haskell/tasty-golden-2.2
		>=dev-haskell/turtle-1.5 )
"
