# Copyright 1999-2020 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=7

# ebuild generated by hackport 0.6.4

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Closable, fair, single-wakeup channel type that avoids 0 reader space leaks"
HOMEPAGE="https://github.com/merijn/broadcast-chan"
SRC_URI="https://hackage.haskell.org/package/${P}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="sync +threaded"

RDEPEND=">=dev-haskell/unliftio-core-0.1.1:=[profile?]
	>=dev-lang/ghc-7.8.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.18.1.3
"

PATCHES=("${FILESDIR}"/${PN}-0.2.1-unlift-io-2.0.patch)

src_prepare() {
	default

	cabal_chdeps \
		'unliftio-core >= 0.1.1 && < 0.2' 'unliftio-core >= 0.1.1'
}

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag sync sync) \
		$(cabal_flag threaded threaded)
}
