# Copyright 1999-2019 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# ebuild generated by hackport 0.2.17.9999

EAPI=7

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="A Haskell binding to a subset of the GD graphics library"
HOMEPAGE="https://hackage.haskell.org/package/gd"
SRC_URI="https://hackage.haskell.org/package/${P}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64"
IUSE="jpeg png"

RDEPEND=">=dev-lang/ghc-6.12.2
		dev-libs/expat
		media-libs/fontconfig
		media-libs/freetype:2
		media-libs/gd:2[jpeg?,png?,zlib]"
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.2"
