# Copyright 1999-2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.0.0.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Adaptation of the monad-time library for the effectful ecosystem"
HOMEPAGE="https://hackage.haskell.org/package/monad-time-effectful"

LICENSE="MIT"
SLOT="0/${PV}"
KEYWORDS="~amd64"

RDEPEND=">=dev-haskell/effectful-core-1.0.0.0:=[profile?] <dev-haskell/effectful-core-3.0.0.0:=[profile?]
	>=dev-haskell/monad-time-0.4.0.0:=[profile?]
	>=dev-lang/ghc-9.0.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
"
