# Copyright 1999-2022 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.7.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="GenValidity support for Scientific"
HOMEPAGE="https://github.com/NorfairKing/validity#readme"
SRC_URI="https://hackage.haskell.org/package/${P}/${P}.tar.gz"

LICENSE="MIT"
SLOT="0/${PV}"
KEYWORDS="~amd64"

RDEPEND=">=dev-haskell/genvalidity-1.0:=[profile?]
	dev-haskell/quickcheck:=[profile?]
	dev-haskell/scientific:=[profile?]
	>=dev-haskell/validity-0.5:=[profile?]
	>=dev-haskell/validity-scientific-0.2:=[profile?]
	>=dev-lang/ghc-8.4.3:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-2.2.0.1
	test? ( dev-haskell/genvalidity-hspec
		dev-haskell/hspec )
"
