# Copyright 1999-2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.0.0.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Formats package descriptions"
HOMEPAGE="https://hackage.haskell.org/package/cabal-gild"

LICENSE="MIT"
SLOT="0/${PV}"
KEYWORDS="~amd64"

RDEPEND=">=dev-haskell/cabal-3.6.0.0:=[profile?]
	>=dev-haskell/parsec-3.1.14.0:=[profile?] <dev-haskell/parsec-3.2:=[profile?]
	>=dev-lang/ghc-9.2.4:=
	>=dev-haskell/text-1.2.5.0:=[profile?] <dev-haskell/text-2.2:=[profile?]
"
DEPEND="${RDEPEND}
	test? ( >=dev-haskell/hspec-2.11.7 <dev-haskell/hspec-2.12
		>=dev-haskell/temporary-1.3 <dev-haskell/temporary-1.4 )
"

src_configure() {
	haskell-cabal_src_configure \
		--flags=pedantic
}
