# Copyright 1999-2022 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.6.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Haskell bindings to the terminfo library"
HOMEPAGE="https://github.com/judah/terminfo"

LICENSE="BSD"
SLOT="0/${PV}"
# keep in sync with ghc-8.8 and ghc 8.10
KEYWORDS="~amd64 ~x86"

RDEPEND=">=dev-lang/ghc-8.0.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.24.0.0
"

CABAL_CORE_LIB_GHC_PV="8.10.6 8.10.7 9.0.1"
