# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.1.0.9999

CABAL_FEATURES=""
inherit haskell-cabal

DESCRIPTION="Whitespace, an esoteric programming language"
HOMEPAGE="https://github.com/haroldl/whitespace-nd"

LICENSE="GPL-2"
SLOT="0"
KEYWORDS="~amd64 ~x86"

RDEPEND="dev-haskell/random:=
	>=dev-lang/ghc-9.0.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
"

PATCHES=("${FILESDIR}"/${P}-ghc-7.10.patch)
