# Copyright 1999-2020 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=7

# ebuild generated by hackport 0.5.6.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Data structures and algorithms for working with 2D graphics"
HOMEPAGE="http://gloss.ouroborus.net"
SRC_URI="https://hackage.haskell.org/package/${P}/${P}.tar.gz"

LICENSE="MIT"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/gloss-1.13:=[profile?] <dev-haskell/gloss-1.14:=[profile?]
	>=dev-lang/ghc-7.10.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.22.2.0
"

src_prepare() {
	cabal_chdeps\
		'base                          >= 4.8 && < 4.12' 'base >=4.8'\
		'containers                    == 0.5.*' 'containers >=0.5 && <0.7'

	default
}
