# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=4

# ebuild generated by hackport 0.2.19

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Workspaces screenshooting utility for XMonad."
HOMEPAGE="http://github.com/supki/xmonad-screenshot"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="MIT"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/gtk-0.12.3[profile?]
		>=dev-lang/ghc-6.10.4
		>=x11-wm/xmonad-0.9[profile?]"
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.8"
